import numpy as np
from calculate_autoNet_yield import isLimiting, giveLimitingCurrency


def findLimRct(j, reactants, shareMatrix, S):
    for m in reactants:
        if isLimiting(m, j, shareMatrix[j], S, reactants):
            return m
    return reactants[0]


def splitByDemandIterative(stoich_matrix, rxnMat, prodMat, sumRxnVec, rho, pi,
                           nutrientSet, Energy, Currency, Core, orgRxns,
                           max_iter=5000, tol=1e-9, tol_loose=1e-4, nutrientSupply=None):
    '''
    Computes the steady-state biomass and energy yield per nutrient molecule.

    The steady state is defined by a continuous external supply of 1 unit/time
    of each nutrient. At every iteration φ[m] represents the total rate of
    supply of metabolite m (external + internal production). The fixed-point
    condition is:

        φ[m] = φ_ext[m] + Σ_{j produces m} v_j · S[j,m] / |S[j,limRct(j)]|

    where φ_ext[m] = 1 for nutrients and 0 otherwise, and each reaction fires
    at the rate determined by its limiting (non-currency) reactant:

        v_j = shareMatrix[j, limRct(j)]
            = |r[j, limRct(j)]| / totalConsumeDemand[limRct(j)] · φ[limRct(j)]

    Unlike splitByDemand, downstream-produced metabolites (including nutrients
    that are regenerated by the network) feed back to all consuming reactions
    across iterations. This correctly accounts for convergent topologies and
    metabolic cycles.

    Thermodynamically valid networks (no futile cycles) have a spectral radius
    ρ < 1 for this map, guaranteeing convergence to a unique finite fixed point.
    Networks with ρ ≥ 1 (which would violate thermodynamic constraints) are
    flagged via a non-converged return.

    Parameters
    ----------
    max_iter : int
        Maximum iterations (default 5000; handles networks with ρ up to ~0.999).
    tol : float
        Tight convergence tolerance (default 1e-9).
    tol_loose : float
        Fallback tolerance used if max_iter is reached without tight convergence.
        If the final delta is within tol_loose the result is still returned,
        flagged as approximate.  If delta > tol_loose the iteration is judged
        not converged and (None, None, False) is returned (default 1e-4).

    Returns
    -------
    (runningE, runningB, viable)  if converged (tight or loose) and all core
                                  metabolites produced
    (None, None, False)           if diverged (φ > 1e6) or not converged within
                                  max_iter even at loose tolerance
    '''
    nMets      = len(np.transpose(stoich_matrix))
    activeRxns = np.array(orgRxns, dtype=int)
    nActive    = len(activeRxns)

    r    = np.copy(rho[activeRxns])
    S    = np.copy(stoich_matrix[activeRxns])
    rMat = np.copy(rxnMat[activeRxns])
    pMat = np.copy(prodMat[activeRxns])

    # Consuming demand per metabolite (negative entries of r only).
    # Fixed across iterations — used to allocate φ proportionally.
    consume_r          = np.where(r < 0, r, 0.0)               # (nActive, nMets)
    totalConsumeDemand = np.abs(np.sum(consume_r, axis=0))      # (nMets,)

    # φ[m] = total rate of supply of metabolite m.
    # Start with external nutrient supply only; internal production accumulates.
    phi = np.zeros(nMets)
    phi[nutrientSet] = 1.0

    # ── Fixed-point iteration ────────────────────────────────────────────────
    # Divergence threshold: for any thermodynamically valid network the
    # fixed-point φ* is O(1)–O(10).  If any component exceeds PHI_MAX the
    # iteration is diverging (spectral radius > 1); we return immediately.
    PHI_MAX = 1e6

    converged = False
    for _ in range(max_iter):
        phi_old = phi.copy()

        # Step 1: distribute φ[m] among consuming reactions proportionally.
        shareMatrix = np.zeros((nActive, nMets), dtype=float)
        valid = totalConsumeDemand > 0
        shareMatrix[:, valid] = (consume_r[:, valid] * phi[valid]) / totalConsumeDemand[valid]
        shareMatrix[:, Currency] = -1       # currency always fully available

        # Step 2: accumulate production.
        # φ_new starts with the continuous external supply (1 unit/time for
        # each nutrient).  Reactions ADD their output on top — including any
        # reaction that happens to regenerate a nutrient metabolite — so that
        # nutrient recycling is fully reflected in the steady-state flux.
        phi_new = np.zeros(nMets)
        phi_new[nutrientSet] = 1.0          # external supply term
        if nutrientSupply:
            for met, supply in nutrientSupply.items():
                phi_new[met] = supply

        for j in range(nActive):
            rs = np.where(rMat[j])[0]
            ps = np.where(pMat[j])[0]
            reactants = [m for m in rs if m not in Currency]
            products  = [m for m in ps if m not in Currency]

            # Identify limiting substrate.
            if not reactants:
                limRct  = giveLimitingCurrency(r, j)
                limFlux = -1.0              # currency is unlimited
            else:
                limRct  = findLimRct(j, reactants, shareMatrix, S)
                limFlux = shareMatrix[j, limRct]
                if limFlux == 0:
                    continue                # no substrate available yet

            # Add this reaction's production to φ_new.
            for m in products:
                phi_new[m] += limFlux * S[j, m] / S[j, limRct]

        phi = phi_new

        # Divergence check: ρ(M) > 1 networks grow without bound.
        if not np.all(np.isfinite(phi)) or np.max(phi) > PHI_MAX:
            return None, None, False

        if np.max(np.abs(phi - phi_old)) < tol:
            converged = True
            break

    if not converged:
        # Not converged within max_iter.  Accept if within loose tolerance
        # (slow but finite convergence), otherwise discard.
        if np.max(np.abs(phi - phi_old)) > tol_loose:
            return None, None, False

    # ── Final pass: compute E, B, and core coverage from converged φ ────────
    shareMatrix = np.zeros((nActive, nMets), dtype=float)
    valid = totalConsumeDemand > 0
    shareMatrix[:, valid] = (consume_r[:, valid] * phi[valid]) / totalConsumeDemand[valid]
    shareMatrix[:, Currency] = -1

    runningE, runningB = 0.0, 0.0
    isCoreProduced = np.zeros(nMets)

    for j in range(nActive):
        rs = np.where(rMat[j])[0]
        ps = np.where(pMat[j])[0]
        reactants = [m for m in rs if m not in Currency]

        if not reactants:
            limRct  = giveLimitingCurrency(r, j)
            limFlux = -1.0
        else:
            limRct  = findLimRct(j, reactants, shareMatrix, S)
            limFlux = shareMatrix[j, limRct]
            if limFlux == 0:
                continue

        mets = np.append(rs, ps)
        for m in mets[np.where(np.isin(mets, np.array(Core + Energy)))]:
            ratio = S[j, m] / S[j, limRct]
            if m in Energy:
                runningE += limFlux * ratio
            elif m in Core:
                if m in ps:
                    isCoreProduced[m] = 1
                runningB += limFlux * ratio

    if isCoreProduced[Core].all():
        return runningE, runningB, True
    else:
        return None, None, False
